name: Unit Tests
permissions: read-all

on:
  workflow_dispatch:
  merge_group:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEBIAN_FRONTEND: noninteractive
  CMAKE_GENERATOR: Ninja
  DEFAULT_CXX_STANDARD: 23
  DEFAULT_LLVM_VERSION: 22
  DEFAULT_GCC_VERSION: 14
  UV_CACHE_DIR: /tmp/.uv-cache
  PIPX_BIN_DIR: /tmp/.pipx_bin

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_and_test_24:
    runs-on: &runner ${{ github.repository_owner == 'intel' && 'intel-' || '' }}ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        compiler: [clang]
        version: [18]
        cxx_standard: [23]
        stdlib: [libstdc++, libc++]
        build_type: [Debug]
        include:
          - compiler: clang
            cc: "clang"
            cxx: "clang++"
            cxx_flags: "-stdlib=libstdc++"
          - version: 18
            compiler: clang
            toolchain_root: "/usr/lib/llvm-18"
          - version: 18
            compiler: clang
            stdlib: libc++
            cxx_flags: "-stdlib=libc++"

    steps:
      - uses: &checkout actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install build tools
        run: |
          if [[ "${{matrix.compiler}}" == "clang" ]]; then
            DISTRO=$(lsb_release -cs)
            wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
            sudo add-apt-repository -y deb "https://apt.llvm.org/$DISTRO/" "llvm-toolchain-$DISTRO-${{matrix.version}}" main
            sudo apt update && sudo apt install -y pipx ninja-build clang-${{matrix.version}} libc++-${{matrix.version}}-dev libc++abi-${{matrix.version}}-dev
          else
            sudo apt update && sudo apt install -y pipx ninja-build gcc-${{matrix.version}} g++-${{matrix.version}}
          fi

      - &install_uv
        name: Install uv
        run: |
          pipx install uv
          echo "$PIPX_BIN_DIR" >> "$GITHUB_PATH"

      - &restore_uv_cache
        name: Restore uv cache
        env:
          cache-name: uv-cache-0
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{env.UV_CACHE_DIR}}
          key: ${{runner.os}}-${{env.cache-name}}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{runner.os}}-${{env.cache-name}}-${{ hashFiles('uv.lock') }}
            ${{runner.os}}-${{env.cache-name}}-

      - &setup_python
        name: Setup python venv
        working-directory: ${{github.workspace}}
        run: |
          uv venv -c
          source .venv/bin/activate
          uv sync
          echo "$(pwd)/.venv/bin" >> "$GITHUB_PATH"

      - &restore_cpm_cache
        name: Restore CPM cache
        env:
          cache-name: cpm-cache-0
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/cpm-cache
          key: ${{runner.os}}-${{env.cache-name}}-${{ hashFiles('**/CMakeLists.txt', 'cmake/**') }}
          restore-keys: |
            ${{runner.os}}-${{env.cache-name}}-${{ hashFiles('**/CMakeLists.txt', 'cmake/**') }}
            ${{runner.os}}-${{env.cache-name}}-

      - name: Configure CMake
        env:
          CC: ${{matrix.toolchain_root}}/bin/${{matrix.cc}}
          CXX: ${{matrix.toolchain_root}}/bin/${{matrix.cxx}}
        run: cmake -B ${{github.workspace}}/build -DCMAKE_CXX_STANDARD=${{matrix.cxx_standard}} -DCMAKE_CXX_FLAGS_INIT=${{matrix.cxx_flags}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCPM_SOURCE_CACHE=~/cpm-cache

      - name: Build unit tests
        run: |
          cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} -v -t build_unit_tests

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: |
          ctest --output-on-failure -j -C ${{matrix.build_type}}

      - &minimize_uv_cache
        name: Minimize uv cache
        run: uv cache prune --ci


